### ISSUE TITLE
esc-pos-encoder error with NODE_MODULE_VERSION

### ISSUE THREAD

**Issue by 22fey** [NielsLeenheer/EscPosEncoder#94]
i'm using this npm for my electron cashie app, and i tried **npm install esc-pos-encoder** and  **npm install esc-pos-encoder --save** command on VScode terminal, but when i run my electron app the esc-pos-encoder got an error with canvas.node, said that the NODE_MODULE_VERSION 116 require. From what i've seen, the latest nodejs version is 20.4.0 that has NODE_MODULE_VERSION 115. 
So, how i should resolve this problem ? thx!

**Comment by mateomarconi** [comment]
Im having the same issue but using node version 18.

I have tried npm rebuild without success.

Error: The module '/app/node_modules/canvas/build/Release/canvas.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 108. This version of Node.js requires
NODE_MODULE_VERSION 93. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.dlopen (pkg/prelude/bootstrap.js:2251:28)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1189:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.require (pkg/prelude/bootstrap.js:1851:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/app/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._compile (pkg/prelude/bootstrap.js:1890:32)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.require (pkg/prelude/bootstrap.js:1851:31)
    at require (node:internal/modules/cjs/helpers:102:18) {
  code: 'ERR_DLOPEN_FAILED'
}

**Comment by NielsLeenheer** [comment]
The current version of EscPosEncoder has a dependency on Node Canvas, which can be hard to install in some instances. Instructions for installing can be found here: https://github.com/Automattic/node-canvas

The upcoming version no longer has this dependancy and will work with many different image libraries.

**Comment by mateomarconi** [comment]
@NielsLeenheer do you know in which release number? I am trying to use 2.0.2 but it still erroing out by canvas. Thank you!
